import { contextBridge, ipcRenderer } from 'electron'
import type { Api } from '../shared/types'
import type { AiEvent } from '../shared/types'

const api: Api = {
  ping: () => ipcRenderer.invoke('ping'),
  'auth:login': (pin) => ipcRenderer.invoke('auth:login', pin),
  'sales:create': (payload) => ipcRenderer.invoke('sales:create', payload),
  'sales:createCaptainOrder': (payload) => ipcRenderer.invoke('sales:createCaptainOrder', payload),
  'sales:void': (id, reason) => ipcRenderer.invoke('sales:void', id, reason),
  'sales:list': (filters) => ipcRenderer.invoke('sales:list', filters),
  'sales:get': (id) => ipcRenderer.invoke('sales:get', id),
  'sales:listByDate': (date) => ipcRenderer.invoke('sales:listByDate', date),
  'sales:getById': (id) => ipcRenderer.invoke('sales:getById', id),
  'expenses:create': (payload) => ipcRenderer.invoke('expenses:create', payload),
  'expenses:update': (id, payload) => ipcRenderer.invoke('expenses:update', id, payload),
  'expenses:delete': (id) => ipcRenderer.invoke('expenses:delete', id),
  'expenses:list': (filters) => ipcRenderer.invoke('expenses:list', filters),
  'reimbursements:create': (payload) => ipcRenderer.invoke('reimbursements:create', payload),
  'reimbursements:list': (start, end) => ipcRenderer.invoke('reimbursements:list', start, end),
  'reimbursements:delete': (id) => ipcRenderer.invoke('reimbursements:delete', id),
  'till:open': (float) => ipcRenderer.invoke('till:open', float),
  'till:close': (counted) => ipcRenderer.invoke('till:close', counted),
  'till:current': () => ipcRenderer.invoke('till:current'),
  'till:countCash': () => ipcRenderer.invoke('till:countCash'),
  'inventory:recordPurchase': (payload) => ipcRenderer.invoke('inventory:recordPurchase', payload),
  'inventory:byDate': (date) => ipcRenderer.invoke('inventory:byDate', date),
  'inventory:byDateRange': (start, end) => ipcRenderer.invoke('inventory:byDateRange', start, end),
  'inventory:dailyTotal': (date) => ipcRenderer.invoke('inventory:dailyTotal', date),
  'waste:record': (payload) => ipcRenderer.invoke('waste:record', payload),
  'waste:byDate': (date) => ipcRenderer.invoke('waste:byDate', date),
  'waste:byDateRange': (start, end) => ipcRenderer.invoke('waste:byDateRange', start, end),
  'waste:byItem': (start, end) => ipcRenderer.invoke('waste:byItem', start, end),
  'waste:dailyTotal': (date) => ipcRenderer.invoke('waste:dailyTotal', date),
  'reports:daily': (start, end) => ipcRenderer.invoke('reports:daily', start, end),
  'reports:monthly': (year) => ipcRenderer.invoke('reports:monthly', year),
  'reports:categoryBreakdown': (start, end) => ipcRenderer.invoke('reports:categoryBreakdown', start, end),
  'reports:itemPerformance': (start, end) => ipcRenderer.invoke('reports:itemPerformance', start, end),
  'reports:debtSummary': () => ipcRenderer.invoke('reports:debtSummary'),
  'reports:sales': (start, end) => ipcRenderer.invoke('reports:sales', start, end),
  'reports:tillSummary': (tillSessionId) => ipcRenderer.invoke('reports:tillSummary', tillSessionId),
  'reports:exportCsv': (range) => ipcRenderer.invoke('reports:exportCsv', range),
  'items:list': (filters) => ipcRenderer.invoke('items:list', filters),
  'items:upsert': (payload) => ipcRenderer.invoke('items:upsert', payload),
  'items:setOutOfStock': (id, outOfStock) => ipcRenderer.invoke('items:setOutOfStock', id, outOfStock),
  'items:delete': (id) => ipcRenderer.invoke('items:delete', id),
  'categories:list': (activeOnly) => ipcRenderer.invoke('categories:list', activeOnly),
  'categories:upsert': (payload) => ipcRenderer.invoke('categories:upsert', payload),
  'categories:delete': (id) => ipcRenderer.invoke('categories:delete', id),
  'attributes:list': (filters) => ipcRenderer.invoke('attributes:list', filters),
  'attributes:upsert': (payload) => ipcRenderer.invoke('attributes:upsert', payload),
  'attributes:delete': (id) => ipcRenderer.invoke('attributes:delete', id),
  'attributes:saveValues': (payload) => ipcRenderer.invoke('attributes:saveValues', payload),
  'settings:get': () => ipcRenderer.invoke('settings:get'),
  'settings:update': (partial) => ipcRenderer.invoke('settings:update', partial),
  'users:setPin': (userId, oldPin, newPin) => ipcRenderer.invoke('users:setPin', userId, oldPin, newPin),
  'users:list': () => ipcRenderer.invoke('users:list'),
  'users:create': (payload) => ipcRenderer.invoke('users:create', payload),
  'users:update': (payload) => ipcRenderer.invoke('users:update', payload),
  'users:resetPin': (payload) => ipcRenderer.invoke('users:resetPin', payload),
  'backup:export': () => ipcRenderer.invoke('backup:export'),
  'backup:import': () => ipcRenderer.invoke('backup:import'),
  'system:status': () => ipcRenderer.invoke('system:status'),
  'system:purge': () => ipcRenderer.invoke('system:purge'),
  'setup:save': (payload) => ipcRenderer.invoke('setup:save', payload),
  'debts:listOpen': () => ipcRenderer.invoke('debts:listOpen'),
  'debts:recordPayment': (payload) => ipcRenderer.invoke('debts:recordPayment', payload),
  'debts:writeOff': (payload) => ipcRenderer.invoke('debts:writeOff', payload),
  'debts:writeOffs': (sale_id) => ipcRenderer.invoke('debts:writeOffs', sale_id),
  'debts:customerBalances': () => ipcRenderer.invoke('debts:customerBalances'),
  'debts:customerDetail': (customerName) => ipcRenderer.invoke('debts:customerDetail', customerName),
  'debts:balanceByName': (customerName) => ipcRenderer.invoke('debts:balanceByName', customerName),
  'debts:payOnAccount': (payload) => ipcRenderer.invoke('debts:payOnAccount', payload),
  'debts:getTotalOwed': (sale_id) => ipcRenderer.invoke('debts:getTotalOwed', sale_id),
  'debts:history': (sale_id) => ipcRenderer.invoke('debts:history', sale_id),
  'assets:list': () => ipcRenderer.invoke('assets:list'),
  'assets:get': (id) => ipcRenderer.invoke('assets:get', id),
  'assets:create': (payload) => ipcRenderer.invoke('assets:create', payload),
  'assets:update': (id, payload) => ipcRenderer.invoke('assets:update', id, payload),
  'assets:dispose': (id, payload) => ipcRenderer.invoke('assets:dispose', id, payload),
  'assets:summary': () => ipcRenderer.invoke('assets:summary'),
  'ai:chat:start': (payload) => ipcRenderer.invoke('ai:chat:start', payload),
  'ai:chat:messages': (sessionId) => ipcRenderer.invoke('ai:chat:messages', sessionId),
  'ai:toolApproval': (payload) => ipcRenderer.invoke('ai:toolApproval', payload),
  'ai:config:get': () => ipcRenderer.invoke('ai:config:get'),
  'ai:config:save': (payload) => ipcRenderer.invoke('ai:config:save', payload),
  'ai:sessions:list': () => ipcRenderer.invoke('ai:sessions:list'),
  'ai:sessions:create': (title) => ipcRenderer.invoke('ai:sessions:create', title),
  'ai:sessions:rename': (id, title) => ipcRenderer.invoke('ai:sessions:rename', id, title),
  'ai:sessions:delete': (id) => ipcRenderer.invoke('ai:sessions:delete', id),
  onAiEvent: (cb) => {
    const listener = (_e: Electron.IpcRendererEvent, event: AiEvent) => cb(event)
    ipcRenderer.on('ai:event', listener)
    return () => ipcRenderer.removeListener('ai:event', listener)
  },
}

contextBridge.exposeInMainWorld('api', api)
