import { contextBridge, ipcRenderer } from 'electron'
import type { Api } from '../shared/types'

const api: Api = {
  ping: () => ipcRenderer.invoke('ping'),
  'auth:login': (pin) => ipcRenderer.invoke('auth:login', pin),
  'sales:create': (payload) => ipcRenderer.invoke('sales:create', payload),
  'sales:void': (id, reason) => ipcRenderer.invoke('sales:void', id, reason),
  'sales:list': (filters) => ipcRenderer.invoke('sales:list', filters),
  'sales:get': (id) => ipcRenderer.invoke('sales:get', id),
  'sales:listByDate': (date) => ipcRenderer.invoke('sales:listByDate', date),
  'sales:getById': (id) => ipcRenderer.invoke('sales:getById', id),
  'customers:create': (name, phone) => ipcRenderer.invoke('customers:create', name, phone),
  'customers:list': () => ipcRenderer.invoke('customers:list'),
  'customers:get': (id) => ipcRenderer.invoke('customers:get', id),
  'payments:create': (payload) => ipcRenderer.invoke('payments:create', payload),
  'payments:list': (customerId) => ipcRenderer.invoke('payments:list', customerId),
  'expenses:create': (payload) => ipcRenderer.invoke('expenses:create', payload),
  'expenses:update': (id, payload) => ipcRenderer.invoke('expenses:update', id, payload),
  'expenses:delete': (id) => ipcRenderer.invoke('expenses:delete', id),
  'expenses:list': (filters) => ipcRenderer.invoke('expenses:list', filters),
  'reimbursements:create': (payload) => ipcRenderer.invoke('reimbursements:create', payload),
  'reimbursements:list': (start, end) => ipcRenderer.invoke('reimbursements:list', start, end),
  'reimbursements:delete': (id) => ipcRenderer.invoke('reimbursements:delete', id),
  'till:open': (float) => ipcRenderer.invoke('till:open', float),
  'till:close': (counted) => ipcRenderer.invoke('till:close', counted),
  'till:current': () => ipcRenderer.invoke('till:current'),
  'till:countCash': () => ipcRenderer.invoke('till:countCash'),
  'inventory:recordPurchase': (payload) => ipcRenderer.invoke('inventory:recordPurchase', payload),
  'inventory:byDate': (date) => ipcRenderer.invoke('inventory:byDate', date),
  'inventory:byDateRange': (start, end) => ipcRenderer.invoke('inventory:byDateRange', start, end),
  'inventory:dailyTotal': (date) => ipcRenderer.invoke('inventory:dailyTotal', date),
  'waste:record': (payload) => ipcRenderer.invoke('waste:record', payload),
  'waste:byDate': (date) => ipcRenderer.invoke('waste:byDate', date),
  'waste:byDateRange': (start, end) => ipcRenderer.invoke('waste:byDateRange', start, end),
  'waste:byItem': (start, end) => ipcRenderer.invoke('waste:byItem', start, end),
  'waste:dailyTotal': (date) => ipcRenderer.invoke('waste:dailyTotal', date),
  'reports:daily': (start, end) => ipcRenderer.invoke('reports:daily', start, end),
  'reports:monthly': (year) => ipcRenderer.invoke('reports:monthly', year),
  'reports:categoryBreakdown': (start, end) => ipcRenderer.invoke('reports:categoryBreakdown', start, end),
  'reports:itemPerformance': (start, end) => ipcRenderer.invoke('reports:itemPerformance', start, end),
  'reports:debtSummary': () => ipcRenderer.invoke('reports:debtSummary'),
  'reports:sales': (start, end) => ipcRenderer.invoke('reports:sales', start, end),
  'reports:tillSummary': (tillSessionId) => ipcRenderer.invoke('reports:tillSummary', tillSessionId),
  'reports:exportCsv': (range) => ipcRenderer.invoke('reports:exportCsv', range),
  'items:list': (filters) => ipcRenderer.invoke('items:list', filters),
  'items:upsert': (payload) => ipcRenderer.invoke('items:upsert', payload),
  'items:setOutOfStock': (id, outOfStock) => ipcRenderer.invoke('items:setOutOfStock', id, outOfStock),
  'items:delete': (id) => ipcRenderer.invoke('items:delete', id),
  'categories:list': (activeOnly) => ipcRenderer.invoke('categories:list', activeOnly),
  'categories:upsert': (payload) => ipcRenderer.invoke('categories:upsert', payload),
  'categories:delete': (id) => ipcRenderer.invoke('categories:delete', id),
  'attributes:list': (filters) => ipcRenderer.invoke('attributes:list', filters),
  'attributes:upsert': (payload) => ipcRenderer.invoke('attributes:upsert', payload),
  'attributes:delete': (id) => ipcRenderer.invoke('attributes:delete', id),
  'attributes:saveValues': (payload) => ipcRenderer.invoke('attributes:saveValues', payload),
  'settings:get': () => ipcRenderer.invoke('settings:get'),
  'settings:update': (partial) => ipcRenderer.invoke('settings:update', partial),
  'users:setPin': (userId, oldPin, newPin) => ipcRenderer.invoke('users:setPin', userId, oldPin, newPin),
  'backup:export': () => ipcRenderer.invoke('backup:export'),
  'backup:import': () => ipcRenderer.invoke('backup:import'),
  'debts:listOpen': () => ipcRenderer.invoke('debts:listOpen'),
  'debts:recordPayment': (payload) => ipcRenderer.invoke('debts:recordPayment', payload),
  'debts:getTotalOwed': (sale_id) => ipcRenderer.invoke('debts:getTotalOwed', sale_id),
  'debts:history': (sale_id) => ipcRenderer.invoke('debts:history', sale_id),
}

contextBridge.exposeInMainWorld('api', api)
